macro_tasks:
  macro_task_0:
      #- path:
      #    - [0.0, 0.0, 0.0]
      #  move:
      #    "sleep"
      - path:
          - [1.0, 1.0, 0.0]
        move:
          "push"
  macro_task_1: 
      - path:
          - [0.0, 1.0, 0.0]
        move:
          "sleep"
      - path:
          - [0.0, 0.0, 0.0]
        move:
          "sleep"
